import _ from 'lodash';

import { Descriptor } from '../descriptor';
import { Style } from '../style';

export default function definitions(descriptor: Descriptor, style: Style): string {
  const macroPrefix = _.toUpper(_.snakeCase(descriptor.name));
  return [
    `#ifndef ${macroPrefix}_ALIGNMENT`,
    `${style.indent}#define ${macroPrefix}_ALIGNMENT 64 /* Large enough for AVX-512 */`,
    '#endif',
    '',
    `#ifndef ${macroPrefix}_ASSERT`,
    `${style.indent}#define ${macroPrefix}_ASSERT(condition) assert(condition)`,
    '#endif',
    '',
    `#if defined(${macroPrefix}_ALIGNED_ALLOC) && defined(${macroPrefix}_ALIGNED_FREE) && defined(${macroPrefix}_ALIGNED_REALLOC)`,
    `${style.indent}/* valid */`,
    `#elif !defined(${macroPrefix}_ALIGNED_ALLOC) && !defined(${macroPrefix}_ALIGNED_FREE) && !defined(${macroPrefix}_ALIGNED_REALLOC)`,
    `${style.indent}/* valid */`,
    '#else',
    `${style.indent}#error "Must define all or none of ${macroPrefix}_ALIGNED_ALLOC, ${macroPrefix}_ALIGNED_FREE, and ${macroPrefix}_ALIGNED_REALLOC."`,
    '#endif',
    '',
    `#ifndef ${macroPrefix}_MALLOC_USABLE_SIZE`,
    `${style.indent}#if defined(__APPLE__)`,
    `${style.indent.repeat(2)}#define ${macroPrefix}_MALLOC_USABLE_SIZE(ptr) malloc_size(ptr)`,
    `${style.indent}#elif defined(__linux__)`,
    `${style.indent.repeat(2)}#define ${macroPrefix}_MALLOC_USABLE_SIZE(ptr) malloc_usable_size(ptr)`,
    `${style.indent}#else`,
    `${style.indent.repeat(2)}#define ${macroPrefix}_MALLOC_USABLE_SIZE(ptr)`,
    `${style.indent}#endif`,
    `#endif /* ${macroPrefix}_MALLOC_USABLE_SIZE */`,
    '',
    `#if !defined(${macroPrefix}_ALIGNED_FREE) && !defined(${macroPrefix}_ALIGNED_ALLOC) && !defined(${macroPrefix}_ALIGNED_REALLOC)`,
    `${style.indent}#if defined(__APPLE__) || defined(__linux__)`,
    `${style.indent.repeat(2)}#define ${macroPrefix}_ALIGNED_FREE(ptr) free(ptr)`,
    `${style.indent.repeat(2)}#define ${macroPrefix}_ALIGNED_ALLOC(align, size) aligned_alloc(align, size)`,
    `${style.indent.repeat(2)}#define ${macroPrefix}_ALIGNED_REALLOC(ptr, align, size) do {\\`,
    `${style.indent.repeat(3)}if ((size == 0) || (align <= alignof(max_align_t)))\\`,
    `${style.indent.repeat(3)}{\\`,
    `${style.indent.repeat(4)}return realloc(ptr, size);\\`,
    `${style.indent.repeat(3)}}\\`,
    `${style.indent.repeat(3)}size_t new_size = (size + (align - 1)) & (~(align - 1));\\`,
    `${style.indent.repeat(3)}void *new_ptr = aligned_alloc(align, new_size);\\`,
    `${style.indent.repeat(3)}if (new_ptr != NULL)\\`,
    `${style.indent.repeat(3)}{\\`,
    `${style.indent.repeat(4)}size_t old_usable_size = ${macroPrefix}_MALLOC_USABLE_SIZE(ptr);\\`,
    `${style.indent.repeat(4)}size_t copy_size = new_size < old_usable_size ? new_size : old_usable_size;\\`,
    `${style.indent.repeat(4)}if (ptr != NULL)\\`,
    `${style.indent.repeat(4)}{\\`,
    `${style.indent.repeat(5)}memcpy(new_ptr, ptr, copy_size);\\`,
    `${style.indent.repeat(5)}free(ptr);\\`,
    `${style.indent.repeat(4)}}\\`,
    `${style.indent.repeat(3)}}\\`,
    `${style.indent.repeat(3)}return new_ptr;\\`,
    `${style.indent.repeat(2)}} while(0)`,
    `${style.indent}#elif defined(_MSC_VER)`,
    `${style.indent.repeat(2)}#define ${macroPrefix}_ALIGNED_FREE(ptr) _aligned_free(ptr)`,
    `${style.indent.repeat(2)}#define ${macroPrefix}_ALIGNED_ALLOC(align, size) _aligned_alloc(size, align)`,
    `${style.indent.repeat(
      2
    )}#define ${macroPrefix}_ALIGNED_REALLOC(ptr, align, size) _aligned_realloc(ptr, size, align);`,
    `${style.indent}#else`,
    `${style.indent.repeat(2)}#define ${macroPrefix}_ALIGNED_FREE(ptr) free(ptr)`,
    `${style.indent.repeat(2)}#define ${macroPrefix}_ALIGNED_ALLOC(align, size) malloc(size)`,
    `${style.indent.repeat(2)}#define ${macroPrefix}_ALIGNED_REALLOC(ptr, align, size) realloc(ptr, size)`,
    `${style.indent}#endif`,
    '#endif'
  ].join('\n');
}
