#!/usr/bin/bash -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source ${SCRIPT_DIR}/common.sh


HEADER=$(cat<<EOM
/**
 * THIS IS CODE-GENERATED by scripts/prebuild.sh
 * DO NOT EDIT!
 **/
EOM
)

CONSTANTS_GENERATOR_JS=$(cat<<EOM

EOM
)


cd $REPO_DIR

#######################################################################################################

info Generating 'src/descriptor.ts'
cat << EOF > src/descriptor.ts
${HEADER}

/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-extraneous-class */
/* eslint-disable @typescript-eslint/no-unused-vars */

$(pnpm exec quicktype --lang ts --src-lang schema docs/schema/descriptor.json --nice-property-names)
EOF
pnpm exec eslint --fix src/descriptor.ts

#######################################################################################################

info Generating 'src/constants.ts'
cat << EOF > src/constants.ts
${HEADER}

$(node ${SCRIPT_DIR}/genConstants.js)
EOF
pnpm exec eslint --fix src/constants.ts

#######################################################################################################

success ${BASH_SOURCE[0]} completed successfully!
