#!/usr/bin/bash

ROOT=$(git rev-parse --show-toplevel)

cd $ROOT

#######################################################################################################

echo Generating 'src/descrioptor.ts'
npx quicktype -o src/descriptor.ts --src-lang schema docs/schema/descriptor.json

#######################################################################################################

echo Generating 'src/constants.ts'
echo "
/**
 * THIS IS CODE-GENERATED by scripts/prebuild.sh
 * DO NOT EDIT!
 **/

export class Constants {
  static readonly AUTHOR: string = '$(node -p "require('./package.json').author")';
  static readonly DESCRIPTION: string = '$(node -p "require('./package.json').description")';
  static readonly HOMEPAGE: string = '$(node -p "require('./package.json').homepage")';
  static readonly LICENSE: string = '$(node -p "require('./package.json').license")';
  static readonly NAME: string = '$(node -p "require('./package.json').name")';
  static readonly RELEASED_DATE: string = '$(node -p "(new Date()).toUTCString()")';
  static readonly RELEASED_YEAR: number = $(node -p "(new Date()).getUTCFullYear()");
  static readonly VERSION: string = '$(node -p "require('./package.json').version")';
}
" > src/constants.ts

#######################################################################################################
