#!/usr/bin/bash -e

ROOT=$(git rev-parse --show-toplevel)
HEADER=$(cat<<EOM
/**
 * THIS IS CODE-GENERATED by scripts/prebuild.sh
 * DO NOT EDIT!
 **/
EOM
)


cd $ROOT

#######################################################################################################

echo Generating 'src/descriptor.ts'
cat << EOF > src/descriptor.ts
${HEADER}

/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-extraneous-class */
/* eslint-disable @typescript-eslint/no-unused-vars */

$(npx quicktype --lang ts --src-lang schema docs/schema/descriptor.json --nice-property-names)
EOF

#######################################################################################################

echo Generating 'src/constants.ts'
cat << EOF > src/constants.ts
${HEADER}

const AUTHOR: string = '$(node -p "require('./package.json').author")';
const DESCRIPTION: string = '$(node -p "require('./package.json').description")';
const HOMEPAGE: string = '$(node -p "require('./package.json').homepage")';
const LICENSE: string = '$(node -p "require('./package.json').license")';
const NAME: string = '$(node -p "require('./package.json').name")';
const RELEASED_DATE: string = '$(node -p "(new Date()).toUTCString()")';
const RELEASED_YEAR: number = $(node -p "(new Date()).getUTCFullYear()");
const VERSION: string = '$(node -p "require('./package.json').version")';

export const Constants = {
  AUTHOR,
  DESCRIPTION,
  HOMEPAGE,
  LICENSE,
  NAME,
  RELEASED_DATE,
  RELEASED_YEAR,
  VERSION
};
EOF

#######################################################################################################
